<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>Com.Appium</groupId>
	<artifactId>MobileTestingPractice</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<dependencies>
		<!--  Source: https://mvnrepository.com/artifact/io.appium/java-client  -->
		<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			<version>10.0.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>tech.grasshopper</groupId>
			<artifactId>extentreports-cucumber7-adapter</artifactId>
			<version>1.14.0</version>
		</dependency>
		<!--  Source:
		https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java  -->
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>4.43.0</version>
			<scope>compile</scope>
		</dependency>
		<!--  Source: https://mvnrepository.com/artifact/org.testng/testng  -->
		<!--  Source:
		https://mvnrepository.com/artifact/io.cucumber/cucumber-java  -->
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>7.34.3</version>
			<scope>compile</scope>
		</dependency>
		<!--  Cucumber JUnit  -->
		<!--  Source:
		https://mvnrepository.com/artifact/io.cucumber/cucumber-junit  -->
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>7.34.3</version>
			<scope>test</scope>
		</dependency>
		<!--  Source: https://mvnrepository.com/artifact/junit/junit  -->
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-junit-platform-engine</artifactId>
			<version>7.34.3</version>
			<scope>test</scope>
		</dependency>
		<!-- Source:
		https://mvnrepository.com/artifact/org.junit.platform/junit-platform-suite -->
		<dependency>
			<groupId>org.junit.platform</groupId>
			<artifactId>junit-platform-suite</artifactId>
			<version>1.14.2</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>